### ISSUE TITLE
`queue.Full` may be raised by workerthread of ProcessPoolExecutor

### ISSUE THREAD

**Issue by PGijsbers** [PGijsbers/gama#40]
This should be because we terminate the child processes directly, which should not really be done. The reasoning for shutting the processes down directly is so that it frees the resources used with it immediately, instead of waiting for the currently running jobs to finish. Unfortunately, this messes with the `concurrent.futures.ProcessPoolExecutor` clean up logic.

The error isn't always raised, and I don't _think_ it has any major consequences. But I'd like to find a way to terminate the processes _and_ the worker thread correctly but abruptly.
```
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python/3.6.3/lib/python3.6/concurrent/futures/process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "/opt/python/3.6.3/lib/python3.6/concurrent/futures/process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "/opt/python/3.6.3/lib/python3.6/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/opt/python/3.6.3/lib/python3.6/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full
```

**Comment by PGijsbers** [comment]
Other similar errors with likely the same cause:
```
OSError: [WinError 6] The handle is invalid
OSError: handle is closed
BrokenPipeError: [WinError 109] The pipe has been ended
```

**Comment by PGijsbers** [comment]
Should no longer occur with the latest async code.
